version: '3.8'

services:
  web:
    build:
      context: ../ 
      dockerfile: ./back/Dockerfile
    command: bash -c 'alembic upgrade head & while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ../back/.env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
